@startuml ClassDiagram

skinparam classAttributeIconSize 0

abstract class Guerrier{
#String Name
#Float Health
#Float Power
#Float Attack
#Float Resistance
#Float Vitesse 
+Guerrier()
+CalculatePower()
+getHit(int hit)
+Hit()
+ChooseArm()
#armEffect()
}


class Viking extends Guerrier{
}

class Arab extends Guerrier{
}

class Pirate extends Guerrier{
}

class Persian extends Guerrier{
}

abstract class Arme {
#String Name
#Float ResistanceEffect
#Float VitesseEffect
+Arme()
+Bool isMagic()
+float affectHealth(float health);
+float affectAttack(float attack);
+float affectResistance(float resistance);
+float affectVitesse(float vitesse);
}

class Shield extends Arme {
}

class Sword extends Arme {
}

class Axe extends Arme {
}

class Magic_wand extends Arme {

}

enum Difficulty{
  EASY
  INTERMEDIATE
  HARD
}


class Clan {
-String Name
-List<Guerrier> Guerriers
-Double Power
+Clan()
+CalculatePower()
+AddGuerrier()
+RemoveGuerrier()
+showClan()
}

abstract class Bataille{
-Boolean typeJeu
-List<Clan> clans
+Bataille()
+addClan(Clan)
+readClan()
+Simulation()
}

class Bataille2Perso extends Bataille{

}

class BatailleVSpc extends Bataille{
-Difficulty NiveauDifficulte
}

Guerrier "1" --* "*" Clan 
Guerrier"*" o-- "1" Arme 
Bataille "*" -- "2" Clan

@enduml